version: '3'

includes:
  update:
    taskfile: Taskfile-update.yaml

  terraform:
    taskfile: Taskfile-terraform.yaml

tasks:
  default:
    preconditions:
      - sh: which gum
        msg: "'gum' is not installed. do 'task update:gum' to install it."
    silent: true
    cmds:
      - task: choose

  choose:
    vars:
      AREAS:
        sh: |
          task -t {{.ROOT_TASKFILE}} --list -j --sort name |
          jq -r '.tasks[].name' |
          sed -E 's/(.*):[^:]*/\1/' |
          uniq
      AREA:
        sh: gum choose --header="Choose an area" {{.AREAS | catLines}}
      TASKS:
        sh: task --list -j --sort none |
            jq -r '.tasks[] | select(.name | startswith("{{.AREA}}:")) | (.name + "|" + .desc)' |
            column -t -s '|'
      CHOICES: |
        {{range $i, $line := .TASKS | splitLines}}{{$line | quote}} {{end}}
      CHOICE:
        sh: gum choose --header="What task?" {{.CHOICES}}
      TASK:
        sh: echo "{{.CHOICE}}" | sed -E 's/([^ ]+) .*/\1/'
    silent: true
    cmds:
      - gum style "task {{.CHOICE}}" --border=rounded --padding="0 1"
      - task -t {{.ROOT_TASKFILE}} "{{.TASK}}"

  scripts:env:
    desc: Create a new environment using the create-environment script
    cmds:
      - ./scripts/create-environment.sh

  scripts:test-ipam:
    desc: Test IPAM API using the test-ipam-api script
    cmds:
      - ./scripts/test-ipam-api.sh